package atividade1;

/* The following code was generated by JFlex 1.6.1 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/main/resources/rsg3.jflex</tt>
 */
public class Minijava {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\37\1\40\1\3\22\0\1\1\1\44\4\0"+
    "\1\41\1\0\1\52\1\53\1\4\1\45\1\51\1\46\1\50\1\2"+
    "\1\6\11\5\1\0\1\47\1\42\1\43\3\0\22\7\1\30\7\7"+
    "\1\56\1\0\1\57\1\0\1\7\1\0\1\14\1\10\1\16\1\25"+
    "\1\13\1\35\1\32\1\34\1\22\2\7\1\12\1\27\1\15\1\11"+
    "\1\20\1\7\1\31\1\17\1\24\1\21\1\26\1\33\1\23\1\36"+
    "\1\7\1\54\1\0\1\55\7\0\1\37\44\0\1\7\12\0\1\7"+
    "\4\0\1\7\5\0\27\7\1\0\37\7\1\0\u01ca\7\4\0\14\7"+
    "\16\0\5\7\7\0\1\7\1\0\1\7\21\0\165\7\1\0\2\7"+
    "\2\0\4\7\1\0\1\7\6\0\1\7\1\0\3\7\1\0\1\7"+
    "\1\0\24\7\1\0\123\7\1\0\213\7\1\0\255\7\1\0\46\7"+
    "\2\0\1\7\7\0\47\7\11\0\55\7\1\0\1\7\1\0\2\7"+
    "\1\0\2\7\1\0\1\7\10\0\33\7\5\0\3\7\35\0\13\7"+
    "\5\0\112\7\4\0\146\7\1\0\10\7\2\0\12\7\1\0\23\7"+
    "\2\0\1\7\20\0\73\7\2\0\145\7\16\0\66\7\4\0\1\7"+
    "\5\0\56\7\22\0\34\7\104\0\23\7\61\0\200\7\2\0\12\7"+
    "\1\0\23\7\1\0\10\7\2\0\2\7\2\0\26\7\1\0\7\7"+
    "\1\0\1\7\3\0\4\7\2\0\11\7\2\0\2\7\2\0\4\7"+
    "\10\0\1\7\4\0\2\7\1\0\5\7\2\0\14\7\17\0\3\7"+
    "\1\0\6\7\4\0\2\7\2\0\26\7\1\0\7\7\1\0\2\7"+
    "\1\0\2\7\1\0\2\7\2\0\1\7\1\0\5\7\4\0\2\7"+
    "\2\0\3\7\3\0\1\7\7\0\4\7\1\0\1\7\7\0\20\7"+
    "\13\0\3\7\1\0\11\7\1\0\3\7\1\0\26\7\1\0\7\7"+
    "\1\0\2\7\1\0\5\7\2\0\12\7\1\0\3\7\1\0\3\7"+
    "\2\0\1\7\17\0\4\7\2\0\12\7\21\0\3\7\1\0\10\7"+
    "\2\0\2\7\2\0\26\7\1\0\7\7\1\0\2\7\1\0\5\7"+
    "\2\0\11\7\2\0\2\7\2\0\3\7\10\0\2\7\4\0\2\7"+
    "\1\0\5\7\2\0\12\7\1\0\1\7\20\0\2\7\1\0\6\7"+
    "\3\0\3\7\1\0\4\7\3\0\2\7\1\0\1\7\1\0\2\7"+
    "\3\0\2\7\3\0\3\7\3\0\14\7\4\0\5\7\3\0\3\7"+
    "\1\0\4\7\2\0\1\7\6\0\1\7\16\0\12\7\20\0\4\7"+
    "\1\0\10\7\1\0\3\7\1\0\27\7\1\0\20\7\3\0\10\7"+
    "\1\0\3\7\1\0\4\7\7\0\2\7\1\0\2\7\6\0\4\7"+
    "\2\0\12\7\21\0\3\7\1\0\10\7\1\0\3\7\1\0\27\7"+
    "\1\0\12\7\1\0\5\7\2\0\11\7\1\0\3\7\1\0\4\7"+
    "\7\0\2\7\7\0\1\7\1\0\4\7\2\0\12\7\1\0\2\7"+
    "\16\0\3\7\1\0\10\7\1\0\3\7\1\0\51\7\2\0\10\7"+
    "\1\0\3\7\1\0\5\7\10\0\1\7\10\0\4\7\2\0\12\7"+
    "\12\0\6\7\2\0\2\7\1\0\22\7\3\0\30\7\1\0\11\7"+
    "\1\0\1\7\2\0\7\7\3\0\1\7\4\0\6\7\1\0\1\7"+
    "\1\0\10\7\6\0\12\7\2\0\2\7\15\0\72\7\5\0\17\7"+
    "\1\0\12\7\47\0\2\7\1\0\1\7\2\0\2\7\1\0\1\7"+
    "\2\0\1\7\6\0\4\7\1\0\7\7\1\0\3\7\1\0\1\7"+
    "\1\0\1\7\2\0\2\7\1\0\15\7\1\0\3\7\2\0\5\7"+
    "\1\0\1\7\1\0\6\7\2\0\12\7\2\0\4\7\40\0\1\7"+
    "\27\0\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\12\7\1\0\44\7\4\0\24\7\1\0\22\7\1\0\44\7"+
    "\11\0\1\7\71\0\112\7\6\0\116\7\2\0\46\7\1\0\1\7"+
    "\5\0\1\7\2\0\53\7\1\0\u014d\7\1\0\4\7\2\0\7\7"+
    "\1\0\1\7\1\0\4\7\2\0\51\7\1\0\4\7\2\0\41\7"+
    "\1\0\4\7\2\0\7\7\1\0\1\7\1\0\4\7\2\0\17\7"+
    "\1\0\71\7\1\0\4\7\2\0\103\7\2\0\3\7\40\0\20\7"+
    "\20\0\125\7\14\0\u026c\7\2\0\21\7\1\0\32\7\5\0\113\7"+
    "\3\0\13\7\7\0\15\7\1\0\7\7\13\0\25\7\13\0\24\7"+
    "\14\0\15\7\1\0\3\7\1\0\2\7\14\0\124\7\3\0\1\7"+
    "\4\0\2\7\2\0\12\7\41\0\3\7\2\0\12\7\6\0\130\7"+
    "\10\0\53\7\5\0\106\7\12\0\37\7\1\0\14\7\4\0\14\7"+
    "\12\0\50\7\2\0\5\7\13\0\54\7\4\0\32\7\6\0\12\7"+
    "\46\0\34\7\4\0\77\7\1\0\35\7\2\0\13\7\6\0\12\7"+
    "\15\0\1\7\10\0\17\7\101\0\114\7\4\0\12\7\21\0\11\7"+
    "\14\0\164\7\14\0\70\7\10\0\12\7\3\0\61\7\122\0\3\7"+
    "\1\0\43\7\1\0\2\7\6\0\366\7\6\0\u011a\7\2\0\6\7"+
    "\2\0\46\7\2\0\6\7\2\0\10\7\1\0\1\7\1\0\1\7"+
    "\1\0\1\7\1\0\37\7\2\0\65\7\1\0\7\7\1\0\1\7"+
    "\3\0\3\7\1\0\7\7\3\0\4\7\2\0\6\7\4\0\15\7"+
    "\5\0\3\7\1\0\7\7\53\0\1\37\1\37\25\0\2\7\23\0"+
    "\1\7\34\0\1\7\15\0\1\7\20\0\15\7\63\0\41\7\21\0"+
    "\1\7\4\0\1\7\2\0\12\7\1\0\1\7\3\0\5\7\6\0"+
    "\1\7\1\0\1\7\1\0\1\7\1\0\4\7\1\0\13\7\2\0"+
    "\4\7\5\0\5\7\4\0\1\7\21\0\51\7\u032d\0\64\7\u0716\0"+
    "\57\7\1\0\57\7\1\0\205\7\6\0\11\7\14\0\46\7\1\0"+
    "\1\7\5\0\1\7\2\0\70\7\7\0\1\7\17\0\30\7\11\0"+
    "\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0"+
    "\7\7\1\0\7\7\1\0\7\7\1\0\40\7\57\0\1\7\u01d5\0"+
    "\3\7\31\0\17\7\1\0\5\7\2\0\5\7\4\0\126\7\2\0"+
    "\2\7\2\0\3\7\1\0\132\7\1\0\4\7\5\0\51\7\3\0"+
    "\136\7\21\0\33\7\65\0\20\7\u0200\0\u19b6\7\112\0\u51cd\7\63\0"+
    "\u048d\7\103\0\56\7\2\0\u010d\7\3\0\34\7\24\0\63\7\1\0"+
    "\12\7\1\0\37\7\1\0\123\7\45\0\11\7\2\0\147\7\2\0"+
    "\4\7\1\0\36\7\2\0\2\7\105\0\61\7\30\0\64\7\14\0"+
    "\105\7\13\0\12\7\6\0\30\7\3\0\1\7\4\0\56\7\2\0"+
    "\44\7\14\0\35\7\3\0\101\7\16\0\13\7\6\0\37\7\1\0"+
    "\67\7\11\0\16\7\2\0\12\7\6\0\27\7\3\0\111\7\30\0"+
    "\3\7\2\0\20\7\2\0\5\7\12\0\6\7\2\0\6\7\2\0"+
    "\6\7\11\0\7\7\1\0\7\7\1\0\53\7\1\0\4\7\4\0"+
    "\2\7\132\0\53\7\1\0\2\7\2\0\12\7\6\0\u2ba4\7\14\0"+
    "\27\7\4\0\61\7\u2104\0\u016e\7\2\0\152\7\46\0\7\7\14\0"+
    "\5\7\5\0\14\7\1\0\15\7\1\0\5\7\1\0\1\7\1\0"+
    "\2\7\1\0\2\7\1\0\154\7\41\0\u016b\7\22\0\100\7\2\0"+
    "\66\7\50\0\14\7\4\0\20\7\20\0\16\7\5\0\2\7\30\0"+
    "\3\7\40\0\5\7\1\0\207\7\23\0\12\7\7\0\32\7\4\0"+
    "\1\7\1\0\32\7\13\0\131\7\3\0\6\7\2\0\6\7\2\0"+
    "\6\7\2\0\3\7\43\0\14\7\1\0\32\7\1\0\23\7\1\0"+
    "\2\7\1\0\17\7\2\0\16\7\42\0\173\7\105\0\65\7\210\0"+
    "\1\7\202\0\35\7\3\0\61\7\17\0\1\7\37\0\40\7\20\0"+
    "\33\7\5\0\53\7\5\0\36\7\2\0\44\7\4\0\10\7\1\0"+
    "\5\7\52\0\236\7\2\0\12\7\126\0\50\7\10\0\64\7\234\0"+
    "\u0137\7\11\0\26\7\12\0\10\7\230\0\6\7\2\0\1\7\1\0"+
    "\54\7\1\0\2\7\3\0\1\7\2\0\27\7\12\0\27\7\11\0"+
    "\37\7\141\0\26\7\12\0\32\7\106\0\70\7\6\0\2\7\100\0"+
    "\4\7\1\0\2\7\5\0\10\7\1\0\3\7\1\0\33\7\4\0"+
    "\3\7\4\0\1\7\40\0\35\7\3\0\35\7\43\0\10\7\1\0"+
    "\36\7\31\0\66\7\12\0\26\7\12\0\23\7\15\0\22\7\156\0"+
    "\111\7\u03b7\0\107\7\37\0\12\7\17\0\74\7\25\0\31\7\7\0"+
    "\12\7\6\0\65\7\1\0\12\7\20\0\44\7\2\0\1\7\11\0"+
    "\105\7\13\0\13\7\45\0\22\7\1\0\45\7\170\0\73\7\5\0"+
    "\12\7\7\0\3\7\1\0\10\7\2\0\2\7\2\0\26\7\1\0"+
    "\7\7\1\0\2\7\1\0\5\7\2\0\11\7\2\0\2\7\2\0"+
    "\3\7\11\0\1\7\5\0\7\7\2\0\7\7\3\0\5\7\u010b\0"+
    "\106\7\1\0\1\7\10\0\12\7\246\0\66\7\2\0\11\7\77\0"+
    "\101\7\3\0\1\7\13\0\12\7\46\0\70\7\10\0\12\7\u01d6\0"+
    "\112\7\25\0\1\7\u01c0\0\71\7\u0507\0\u0399\7\147\0\157\7\u0b91\0"+
    "\u042f\7\u33d1\0\u0239\7\7\0\37\7\1\0\12\7\146\0\36\7\2\0"+
    "\5\7\13\0\67\7\11\0\4\7\14\0\12\7\11\0\25\7\5\0"+
    "\23\7\u0370\0\105\7\13\0\57\7\20\0\21\7\u4060\0\2\7\u0bfe\0"+
    "\153\7\5\0\15\7\3\0\11\7\7\0\12\7\3\0\2\7\u14c6\0"+
    "\5\7\3\0\6\7\10\0\10\7\2\0\7\7\36\0\4\7\224\0"+
    "\3\7\u01bb\0\125\7\1\0\107\7\1\0\2\7\2\0\1\7\2\0"+
    "\2\7\2\0\4\7\1\0\14\7\1\0\1\7\1\0\7\7\1\0"+
    "\101\7\1\0\4\7\2\0\10\7\1\0\7\7\1\0\34\7\1\0"+
    "\4\7\1\0\5\7\1\0\1\7\3\0\7\7\1\0\u0154\7\2\0"+
    "\31\7\1\0\31\7\1\0\37\7\1\0\31\7\1\0\37\7\1\0"+
    "\31\7\1\0\37\7\1\0\31\7\1\0\37\7\1\0\31\7\1\0"+
    "\10\7\2\0\62\7\u1000\0\305\7\13\0\7\7\u0529\0\4\7\1\0"+
    "\33\7\1\0\2\7\1\0\1\7\2\0\1\7\1\0\12\7\1\0"+
    "\4\7\1\0\1\7\1\0\1\7\6\0\1\7\4\0\1\7\1\0"+
    "\1\7\1\0\1\7\1\0\3\7\1\0\2\7\1\0\1\7\2\0"+
    "\1\7\1\0\1\7\1\0\1\7\1\0\1\7\1\0\1\7\1\0"+
    "\2\7\1\0\1\7\2\0\4\7\1\0\7\7\1\0\4\7\1\0"+
    "\4\7\1\0\1\7\1\0\12\7\1\0\21\7\5\0\3\7\1\0"+
    "\5\7\1\0\21\7\u0274\0\32\7\6\0\32\7\6\0\32\7\u0e76\0"+
    "\ua6d7\7\51\0\u1035\7\13\0\336\7\u3fe2\0\u021e\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\7\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\2\4\20\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\2"+
    "\1\0\11\5\1\25\11\5\1\26\1\27\1\30\1\0"+
    "\4\5\1\31\3\5\1\32\11\5\1\2\2\5\1\33"+
    "\4\5\1\34\1\35\1\36\1\37\10\5\1\40\5\5"+
    "\1\41\1\42\1\5\1\43\1\5\1\44\1\45\1\46"+
    "\1\5\1\47\1\50\1\51\1\0\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\1\5\1\0\1\5"+
    "\1\0\1\5\2\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\60\0\140\0\60\0\220\0\300\0\300"+
    "\0\360\0\u0120\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240"+
    "\0\u0270\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\60"+
    "\0\u03c0\0\60\0\u03f0\0\u0420\0\60\0\60\0\60\0\60"+
    "\0\60\0\60\0\60\0\60\0\60\0\60\0\60\0\u0450"+
    "\0\u0480\0\u04b0\0\u04e0\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0"+
    "\0\u0600\0\u0630\0\300\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720"+
    "\0\u0750\0\u0780\0\u07b0\0\u07e0\0\60\0\60\0\60\0\u0810"+
    "\0\u0840\0\u0870\0\u08a0\0\u08d0\0\300\0\u0900\0\u0930\0\u0960"+
    "\0\300\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0ab0"+
    "\0\u0ae0\0\u0b10\0\u0480\0\u0b40\0\u0b70\0\300\0\u0ba0\0\u0bd0"+
    "\0\u0c00\0\u0c30\0\300\0\300\0\300\0\300\0\u0c60\0\u0c90"+
    "\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50\0\u0d80\0\u0db0\0\300\0\u0de0"+
    "\0\u0e10\0\u0e40\0\u0e70\0\u0ea0\0\300\0\300\0\u0ed0\0\300"+
    "\0\u0f00\0\300\0\300\0\300\0\u0f30\0\300\0\300\0\300"+
    "\0\u0f60\0\u0f90\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\u1080\0\u10b0"+
    "\0\u10e0\0\u1110\0\u1140\0\u1170\0\u11a0\0\u11d0\0\u1200\0\u1230"+
    "\0\u1260\0\u1290\0\u12c0\0\u12f0\0\u1320\0\u1350\0\60\0\300";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\10\1\12\1\13\1\10\1\14\1\15\1\16"+
    "\1\17\1\10\1\20\1\10\1\21\1\10\1\22\1\23"+
    "\1\24\1\25\1\10\1\26\1\10\1\27\1\10\1\30"+
    "\1\3\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\62\0\1\50\1\0\1\51\60\0\2\6\30\10\26\0"+
    "\32\10\26\0\4\10\1\52\25\10\26\0\6\10\1\53"+
    "\23\10\26\0\5\10\1\54\10\10\1\55\13\10\26\0"+
    "\6\10\1\56\23\10\26\0\5\10\1\57\24\10\26\0"+
    "\17\10\1\60\12\10\26\0\14\10\1\61\15\10\26\0"+
    "\10\10\1\62\17\10\1\63\1\10\26\0\24\10\1\64"+
    "\2\10\1\65\2\10\26\0\4\10\1\66\25\10\26\0"+
    "\7\10\1\67\22\10\26\0\17\10\1\70\11\10\1\71"+
    "\26\0\6\10\1\72\23\10\26\0\27\10\1\73\2\10"+
    "\26\0\7\10\1\74\22\10\62\0\1\75\61\0\1\76"+
    "\57\0\1\77\14\0\3\50\1\0\54\50\4\51\1\100"+
    "\53\51\5\0\4\10\1\101\25\10\26\0\10\10\1\102"+
    "\21\10\26\0\12\10\1\103\17\10\26\0\17\10\1\104"+
    "\12\10\26\0\26\10\1\105\3\10\26\0\7\10\1\106"+
    "\22\10\26\0\7\10\1\107\22\10\26\0\3\10\1\110"+
    "\26\10\26\0\17\10\1\111\12\10\26\0\14\10\1\112"+
    "\15\10\26\0\15\10\1\113\14\10\26\0\15\10\1\114"+
    "\14\10\26\0\15\10\1\115\14\10\26\0\24\10\1\116"+
    "\5\10\26\0\12\10\1\117\17\10\26\0\17\10\1\120"+
    "\12\10\26\0\15\10\1\121\14\10\26\0\5\10\1\122"+
    "\24\10\21\0\2\51\1\123\1\51\1\100\53\51\5\0"+
    "\5\10\1\124\24\10\26\0\25\10\1\125\4\10\26\0"+
    "\6\10\1\126\23\10\26\0\6\10\1\127\23\10\26\0"+
    "\12\10\1\130\17\10\26\0\17\10\1\131\12\10\26\0"+
    "\5\10\1\132\24\10\26\0\6\10\1\133\23\10\26\0"+
    "\12\10\1\134\17\10\26\0\20\10\1\135\11\10\26\0"+
    "\10\10\1\136\21\10\26\0\15\10\1\137\14\10\26\0"+
    "\17\10\1\140\12\10\26\0\14\10\1\141\15\10\26\0"+
    "\5\10\1\142\24\10\26\0\12\10\1\143\17\10\26\0"+
    "\6\10\1\144\23\10\26\0\17\10\1\145\12\10\26\0"+
    "\10\10\1\146\21\10\26\0\12\10\1\147\17\10\26\0"+
    "\15\10\1\150\14\10\26\0\15\10\1\151\14\10\26\0"+
    "\10\10\1\152\21\10\26\0\6\10\1\153\23\10\26\0"+
    "\24\10\1\154\5\10\26\0\6\10\1\155\23\10\26\0"+
    "\6\10\1\156\23\10\26\0\7\10\1\157\22\10\26\0"+
    "\27\10\1\160\2\10\26\0\20\10\1\161\11\10\26\0"+
    "\11\10\1\162\20\10\26\0\11\10\1\163\20\10\26\0"+
    "\25\10\1\164\4\10\26\0\22\10\1\165\7\10\26\0"+
    "\10\10\1\166\21\10\26\0\10\10\1\167\21\10\26\0"+
    "\12\10\1\170\17\10\21\0\3\171\1\0\1\171\32\172"+
    "\2\0\17\171\11\0\1\173\53\0\4\10\1\174\25\10"+
    "\42\0\1\175\43\0\14\10\1\176\15\10\45\0\1\177"+
    "\40\0\17\10\1\200\12\10\21\0\3\201\1\0\33\201"+
    "\2\0\22\201\1\0\1\201\32\202\2\0\17\201\20\0"+
    "\1\203\44\0\13\10\1\204\16\10\52\0\1\205\33\0"+
    "\24\10\1\206\5\10\43\0\1\207\42\0\15\10\1\210"+
    "\14\10\36\0\1\211\47\0\10\10\1\212\21\10\45\0"+
    "\1\213\40\0\17\10\1\214\12\10\33\0\1\215\52\0"+
    "\5\10\1\216\24\10\36\0\1\217\47\0\10\10\1\220"+
    "\21\10\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4992];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\22\1\1\11\1\1\1\11"+
    "\2\1\13\11\1\1\1\0\23\1\3\11\1\0\70\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Minijava(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2666) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Caractere ilegal! '" + yytext() + "' na linha: " + yyline + ", coluna: " + yycolumn);
            }
          case 43: break;
          case 2: 
            { 
            }
          case 44: break;
          case 3: 
            { System.out.println("Token PRODUCT");
            }
          case 45: break;
          case 4: 
            { System.out.println("Literal: \"" + yytext() + "\"");
            }
          case 46: break;
          case 5: 
            { System.out.println("Identifier: \"" + yytext() + "\"");
            }
          case 47: break;
          case 6: 
            { System.out.print(yytext());
            }
          case 48: break;
          case 7: 
            { System.out.println("Token LESS_THEN");
            }
          case 49: break;
          case 8: 
            { System.out.println("Token ASSIGN");
            }
          case 50: break;
          case 9: 
            { System.out.println("Token NEG");
            }
          case 51: break;
          case 10: 
            { System.out.println("Token SUM");
            }
          case 52: break;
          case 11: 
            { System.out.println("Token MINUS");
            }
          case 53: break;
          case 12: 
            { System.out.println("Token SEMI_COMMA");
            }
          case 54: break;
          case 13: 
            { System.out.println("Token DOT");
            }
          case 55: break;
          case 14: 
            { System.out.println("Token COMMA");
            }
          case 56: break;
          case 15: 
            { System.out.println("Token LEFT_PARENTHESES");
            }
          case 57: break;
          case 16: 
            { System.out.println("Token RIGHT_PARENTHESES");
            }
          case 58: break;
          case 17: 
            { System.out.println("Token LEFT_BRACKET");
            }
          case 59: break;
          case 18: 
            { System.out.println("Token RIGHT_BRACKET");
            }
          case 60: break;
          case 19: 
            { System.out.println("Token LEFT_BRACES");
            }
          case 61: break;
          case 20: 
            { System.out.println("Token RIGHT_BRACES");
            }
          case 62: break;
          case 21: 
            { System.out.println("Token IF");
            }
          case 63: break;
          case 22: 
            { System.out.println("Token AND");
            }
          case 64: break;
          case 23: 
            { System.out.println("Token EQUALS");
            }
          case 65: break;
          case 24: 
            { System.out.println("Token NOT_EQUALS");
            }
          case 66: break;
          case 25: 
            { System.out.println("Token NEW");
            }
          case 67: break;
          case 26: 
            { System.out.println("Token INT");
            }
          case 68: break;
          case 27: 
            { System.out.println("Token ELSE");
            }
          case 69: break;
          case 28: 
            { System.out.println("Token TRUE");
            }
          case 70: break;
          case 29: 
            { System.out.println("Token THIS");
            }
          case 71: break;
          case 30: 
            { System.out.println("Token VOID");
            }
          case 72: break;
          case 31: 
            { System.out.println("Token MAIN");
            }
          case 73: break;
          case 32: 
            { System.out.println("Token CLASS");
            }
          case 74: break;
          case 33: 
            { System.out.println("Token WHILE");
            }
          case 75: break;
          case 34: 
            { System.out.println("Token FALSE");
            }
          case 76: break;
          case 35: 
            { System.out.println("Token LENGTH");
            }
          case 77: break;
          case 36: 
            { System.out.println("Token STATIC");
            }
          case 78: break;
          case 37: 
            { System.out.println("Token PUBLIC");
            }
          case 79: break;
          case 38: 
            { System.out.println("Token STRING");
            }
          case 80: break;
          case 39: 
            { System.out.println("Token RETURN");
            }
          case 81: break;
          case 40: 
            { System.out.println("Token BOOLEAN");
            }
          case 82: break;
          case 41: 
            { System.out.println("Token EXTENDS");
            }
          case 83: break;
          case 42: 
            { System.out.println("Token SYSO");
            }
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Minijava [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Minijava scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Minijava(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
